checks:
    php:
        code_rating: true
        duplication: true

tools:
    php_analyzer: true
    php_mess_detector: true
    php_code_sniffer:
        config:
            standard: PSR2
            tab_width: 4
